### ISSUE TITLE
Check references to master

### ISSUE THREAD

**Issue by jennygrahamjones** [guardian/editorial-production-metrics#205]
The master branch of this repository has been migrated to main using the [master-to-main](https://github.com/guardian/master-to-main) tool.

  Some files in the repository contain the word master. Please check the following files and update where required:

  - [ ] [public/styles/base/_helpers.scss](https://github.com/guardian/editorial-production-metrics/blob/main/public/styles/base/_helpers.scss)
- [ ] [public/styles/abstracts/_variables.scss](https://github.com/guardian/editorial-production-metrics/blob/main/public/styles/abstracts/_variables.scss)
- [ ] [docs/addingMetrics.md](https://github.com/guardian/editorial-production-metrics/blob/main/docs/addingMetrics.md)

**Comment by ParisaTork** [comment]
The links in [public/styles/base/_helpers.scss](https://github.com/guardian/editorial-production-metrics/blob/main/public/styles/base/_helpers.scss) and [public/styles/abstracts/_variables.scss](https://github.com/guardian/editorial-production-metrics/blob/main/public/styles/abstracts/_variables.scss) are broken and Jenny fixed [docs/addingMetrics.md](https://github.com/guardian/editorial-production-metrics/blob/main/docs/addingMetrics.md) in #207, so closing.
